- hosts: all
  vars:
    packages:
      - httpd
      - php
      - python3-pip
      - nginx
  tasks:
  - name: "Install packages"
    package:
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"
    tags:
      - install
      - webserver

  - name: "copy webpages"
    copy:
      src: ./index.html
      dest: /var/www/html
      owner: root
      group: root
      mode: '777'
    tags:
      - copy

  - name: "copy http server configuration file"
    copy:
      src: httpd.conf
      dest: /etc/httpd/conf/ 
    notify:
      - restart webserver
    tags:
      - copy
      - config

  handlers:

    - name: "restart webserver"
      service:
        name: httpd
        state: restarted